spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce_db_test}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:085777}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgresSQLDialect
server:
  port: ${APP_PORT:8055}